version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
  - kind/dependency
  - do-not-merge/work-in-progress
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Uno.Core
    versions:
    - 2.1.0
    - 2.2.0
  - dependency-name: Uno.UI
    versions:
    - 3.1.12
    - 3.1.14
    - 3.5.1
  - dependency-name: Moq
    versions:
    - 4.16.0
  commit-message:
    prefix: chore
    include: scope
